GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Second User",
    "username": "second_user"
}

###

GET http://localhost:3000/posts/688ca76253b13abd484a5d2a